# Generated by Django 6.0.8 on 2026-09-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='role',
            field=models.CharField(choices=[('MODERATOR', 'Moderator'), ('PLACEMENT_OFFICER', 'Placement Officer'), ('TPO_INCHARGE', 'T&P Incharge'), ('DEPARTMENT_ADMIN', 'Department Admin'), ('SUPER_ADMIN', 'Super Admin')], default='MODERATOR', max_length=32),
        ),
    ]
