# Generated by Django 6.0.8 on 2026-08-05 05:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=32, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('MODERATOR', 'Moderator'), ('PLACEMENT_OFFICER', 'Placement Officer'), ('DEPARTMENT_ADMIN', 'Department Admin'), ('SUPER_ADMIN', 'Super Admin')], default='MODERATOR', max_length=32)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_secret', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('STUDENT_VERIFICATION', 'Student Verification'), ('CERTIFICATE', 'Certificate'), ('ORGANIZATION', 'Organization'), ('OPPORTUNITY', 'Opportunity')], max_length=32)),
                ('target_id', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='faculty_app.faculty')),
            ],
            options={
                'db_table': 'audit_log_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('org_type', models.CharField(choices=[('COMPANY', 'Company'), ('NGO', 'NGO')], max_length=16)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_organizations', to='faculty_app.faculty')),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('opportunity_type', models.CharField(choices=[('INTERNSHIP', 'Internship'), ('NGO', 'NGO')], max_length=16)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('compensation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('compensation_currency', models.CharField(default='INR', max_length=8)),
                ('is_unpaid', models.BooleanField(default=False)),
                ('work_mode', models.CharField(choices=[('REMOTE', 'Remote'), ('ONSITE', 'Onsite'), ('HYBRID', 'Hybrid')], max_length=16)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('duration_weeks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('application_deadline', models.DateTimeField()),
                ('positions_available', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired')], default='PENDING_APPROVAL', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_opportunities', to='faculty_app.faculty')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_opportunities', to='faculty_app.faculty')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='faculty_app.organization')),
            ],
            options={
                'db_table': 'opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField(db_index=True)),
                ('file_url', models.CharField(max_length=500)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_certificates', to='faculty_app.faculty')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='faculty_app.opportunity')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='faculty_app.organization')),
            ],
            options={
                'db_table': 'certificates',
            },
        ),
        migrations.CreateModel(
            name='StudentVerificationRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField(db_index=True, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('roll_number', models.CharField(db_index=True, max_length=32)),
                ('department', models.CharField(max_length=100)),
                ('year_of_study', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged')], default='PENDING', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_students', to='faculty_app.faculty')),
            ],
            options={
                'db_table': 'student_verification_requests',
            },
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['department'], name='faculty_departm_62c77d_idx'),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['role'], name='faculty_role_952598_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['target_type', 'target_id'], name='audit_log_e_target__e34068_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['verification_status'], name='organizatio_verific_21fa85_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['org_type'], name='organizatio_org_typ_b2fc82_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['status'], name='opportuniti_status_019aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['opportunity_type'], name='opportuniti_opportu_b8dd5f_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['application_deadline'], name='opportuniti_applica_e47269_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['verification_status'], name='certificate_verific_26bbf5_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['student_id'], name='certificate_student_e19697_idx'),
        ),
        migrations.AddIndex(
            model_name='studentverificationrequest',
            index=models.Index(fields=['status'], name='student_ver_status_0ac572_idx'),
        ),
        migrations.AddIndex(
            model_name='studentverificationrequest',
            index=models.Index(fields=['roll_number'], name='student_ver_roll_nu_c780bb_idx'),
        ),
    ]
