# Generated by Django 5.2.17 on 2026-09-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(choices=[('INTERNSHIP', 'Internship'), ('JOB', 'Job'), ('NGO', 'NGO')], max_length=16),
        ),
    ]
